apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: postgresql
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami/charts
    chart: postgresql
    targetRevision: 12.5.6
    helm:
      releaseName: argocd-postgresql
      parameters:
        - name: global.postgresql.auth.database
          value: testdb
        - name: global.postgresql.auth.password
          value: prueba
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true